export { default as About } from './about/About'
export { default as Contact } from './contact/Contact'
export { default as Landing } from './landing/Landing'
export { default as Navbar } from './navbar/Navbar'
export { default as Projects } from './projects/Projects'